name: Non-native builds

on:
  push:
      paths-ignore:
          - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read


jobs:
  freebsd:
    name: 'FreeBSD (${{ matrix.compiler }}, ${{ matrix.arch }})'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - { arch: 'x86_64', compiler: 'clang' }
          #- { arch: 'arm64', compiler: 'clang' }
      fail-fast: false
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: cross-platform-actions/action@cdc9ee69ef84a5f2e59c9058335d9c57bcb4ac86 # v0.25.0
        with:
          operating_system: 'freebsd'
          version: '14.1'
          architecture: ${{ matrix.arch }}
          run: |
            # https://ports.freebsd.org/
            sudo pkg install -y cmake ninja pkgconf tiff curl sqlite3 proj expat png libjpeg-turbo openjpeg swig py311-setuptools py311-numpy py311-pytest py311-pytest-benchmark py311-pytest-env py311-filelock py311-lxml
            cmake -B bld -G Ninja \
              '-DCMAKE_C_COMPILER=${{ matrix.compiler }}' \
              -DCMAKE_UNITY_BUILD=ON \
              -DCMAKE_C_FLAGS=-Werror \
              -DCMAKE_CXX_FLAGS=-Werror
            cmake --build bld --config Debug -j3
            ctest --test-dir bld --build-config Debug -j3
